name: 'GitHub Actions Weather Bot'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash .github/workflows/weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/YULIN' date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 天气预报-YULIN (${{env.REPORT_DATE}})
          html_body: file://result.html
          to: 1468336507@qq.com
          from: GitHub Actions
