name: ikuuu.on网站签到
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 18 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get env'
        run: echo -e "${{ secrets.EMIALANDTELEGRAMBOT }}" > .env
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'
      - run: pip install -r ./src/requirements.txt
      - run: python src/main.py